# Generated by Django 5.0.1 on 2024-01-20 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_mediafile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='board.advertisement'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(upload_to='media_files/'),
        ),
    ]
